### PR TITLE
Refactor [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by jonasfj**
**Don't look at the diff, just at what was added**

This is an outline of how I think we could structure this for more win. Changes:

 * Rename subpackages to `tcqueue`
 * Subpackage `tcqueue` only defines structs (no code)
 * top-level package renamed `taskcluster`
 * Expose clients through interfaces, ie. `taskcluster.Queue` is the interface for queue client
 * `taskcluster.NewQueue(taskcluster.Options{})` creates a new queue client 
 * Options passed to a client object are wrapped in `taskcluster.Options{}`
    * so they are optional,
    * we can add more in the future, and,
    * we can use same options for all client instantiations.
 * Provide mock implementations `taskcluster.MockQueue`
 * Provide logic for automagically refreshing credentials
 * Support `context.Context`
 * Consume abstract metrics interface compatible with statsum client
 * Remove `Task_BuildURL` methods in favor of loosely typed `BuildURL('task', ...)`, these are rarely used and polluting docs doesn't seem worth it, just to avoid the tiny risk of a reliable panic.
 * Possibly drop documentation comments, or maybe only use "title" as documentation comment (in order to keep godoc concise)

Changes for jsonschema2go:
 * No more `tcclient.Time` since `time.Time` can be encoded/decoded as JSON (if this causes problem we'll write custom encoding/decoding logic for structs with this property type)
 * No more `json.RawMessage` always fallback to `map[string]interface{}`
 * Handle `{type: object, additionalProperties: {type: string}}` as `map[string]string`
 * Handle `{anyOf: [{type: object, title: 'reference artifact', ...}, {type: object, title: 'error artifact', ...}]}` as `struct { *ReferenceArtifact, *ErrorArtifact}`. This will require custom encoding/decoding logic for the structs containing these properties.

**Downsides**, with exception of the struct declarations everything is in the top-level `taskcluster` package. This package depends on the subpackages, so we can't use anything from the top-level package in the subpackages. This could cause slightly slower compilation time, but golang is pretty good at throwing away unused code. Upside is fewer namespaces to deal with. You only use the `tcqueue` package if you need access to a request data struct.

@petemoore, I'm not sure how serious I am about doing this... So far lets consider it an observation of things we could improve. There is probably still a few things to tweak. Also not sure when we have time to go do this :)

### CODE REVIEW

**Comment by jonasfj** [comment]
Problems that we have right now:
 * golang tooling can't automatically resolve `tcclient` so you have to manually write `tcclient "github.com/taskcluster/taskcluster-client-go"`
 * `auth` is reserved for namespace, so I have to write: `a := auth.New(&tcclient.Credentials{`
 * `Auth` and `Credentials` are two different packages, this is confusing
 * `tcclient.Credentials` are passed by reference which makes is pointless considering the size (only invites concurrency bugs)

**Comment by jonasfj** [comment]
Just added a custom error type as we currently don't print errors very nicely, we just return generic HTTP errors right now...
This would also make programmatic handling of certain kinds of errors feasible.

**Comment by jonasfj** [comment]
@petemoore, this isn't perfect, it makes me sad that you'll effectively end up always importing all the code and all the subpackages... But that is pretty much the only downside I see. And it's really not that problematic as we don't have that much generated code. Ie. most of the generated code is just construct the route, invoke the `call` function and return parsed values. There might be a bit more generated code to parsing JSON if we need custom implementations... But hopefully most structs won't need that.

So if we can accept the deficiency that all code is loaded all the time, then this is a pretty neat.
Anyways, let me know what you think.

**Comment by petemoore** [comment]
@jonasfj I think we have bigger fish to fry at this point in time. We have a working, reliable client implementation that serves our current workers well, and this feels like digging up a garden rather than serving a real business need. I also am not keen on the complexity of the abstractions, for example the introduction of a type `fetchingAuthorizer` with its own set of methods, feels unnecessarily heavy. I feel creating such levels of abstraction is at odds with the general go philosophy of keeping things simple. Then there is the extensive use of embedding types which feels very much like an antipattern to fake some kind of inheritance model. Then the use of mutexes to guard data rather than signalling via channels or using value types to prevent mutation. It was only a high level read, but it already _feels_ heavy. We saw how the code of generic worker was replaced by 5x as much code in taskcluster worker, with comparable functionality, and I'm concerned this pattern would repeat itself here.

In short, if this addresses an OKR, then maybe there is merit. If not, maybe some parts of the existing client can be tweaked (e.g. moving code between packages, renaming methods, adding monitoring support, making credentials immutable, ... whatever) but writing from scratch seems unnecessary, time-consuming, potentially introduces instability, and possibly results in a much bigger codebase with higher complexity, but without any significant behaviour improvements.

Another option might be to create a new project (like you did with taskcluster-worker and go-got) in a separate repository, so that projects that depend on a client can actively choose to migrate once the new client is proven and stable (to avoid introducing instability into workers and proxies, etc).

We should also learn from the lessons of the python client, where a lot of noise was caused when a rewrite to support async landed directly in the project.

**Comment by jonasfj** [comment]
Yeah, this would be a breaking change... Could easily be a new repo.

My motivation is to remove complexity from tc-worker, by making a better
client we have fewer things to wrap. Right now tc-worker does interfaces
and mock implementations, and it deals with the paper cuts of many of the
JSON decoding/encoding issues addressed here too.

None of this makes life impossible, just a guessbit more complicated than
it had to be. So yeah, this is not a high priority, but an outline for
making things simpler for consumers in some future.

Den 28. feb. 2017 4.32 AM skrev "Pete Moore" <notifications@github.com>:

**Comment by petemoore** [comment]
@jonasfj cool - do you want to create a new repo called `tcclient` or `taskcluster` for this, and we close it here?

**Comment by jonasfj** [comment]
Will do...

**Pull request closed without merging**
