### PR TITLE
Add support for aborting requests with context.Context

### PR DESCRIPTION
**Pull request by jonasfj**

### CODE REVIEW

**Comment by petemoore** [comment]
Can you add a test or two? I don't know the context package but if you can demonstrate that it works as expected, it is ok with me.

**Review by walac — APPROVED** [review]

**Comment by jonasfj** [comment]
Added a test case...
Note. I'm not happy about the API design... it really would have been ideal to either have a:
 * `q = q.WithContext(ctx)` where `q` is an instance of queue client, or,
 * All methods always takes a `context.Context` as argument...

But there is too much mess to clean it up... and make a nice API that's more thread-safe.
And this is no worse than what we already have...

**Comment by jonasfj** [comment]
Also updated API clients to new schema... so tests will pass..

**Comment by jonasfj** [comment]
Somehow I'm guessing the failures are eventually consistent S3, or because I'm using a different golang version...

**Comment by petemoore** [comment]
@jonasfj It looks like other stuff got introduced here, do you know why?

**Comment by jonasfj** [comment]
References changed, so tests wouldn't pass unless I updated reran codegen...

Den 13. apr. 2017 11.48 PM skrev "Pete Moore" <notifications@github.com>:

**Comment by petemoore** [comment]
Note, this means any library that uses taskcluster-client-go now needs at least go 1.7 due to the context library being new in go 1.7.

**Comment by jonasfj** [comment]
go is forward compatible for almost anything... I think it's fair for us to always require the latest golang version..

**Comment by petemoore** [comment]
> go is forward compatible for almost anything... I think it's fair for us to always require the latest golang version..

This is true, it is just something to be aware of. For example, I updated the relengapi-proxy docs to say "go 1.7 is now needed" because previously it built with go 1.5, which is no longer the case, and this caused a contributor to lose some time, not being able to build with strange error messages about a `context` package he didn't know about. This can also be solved by vendoring taskcluster-client-go, but vendoring isn't always a great fit since builds won't then detect when there are changes to production APIs. Generally (not always, of course) I prefer not to vendor the client, as old clients are not guaranteed to work against the latest production services. So it is really just a note to ourselves - when we depend on this library, and we choose intentionally not to vendor the dependency, we should explicitly state the minimum go version required due to this dependency, and if that changes in the client, we should update the projects that depend on it, to state the new minimum version of go that they must now use.

**Comment by walac** [comment]
> go is forward compatible for almost anything... I think it's fair for us to always require the latest golang version..

The problem is that we have automation (docker images) that run with older versions of golang. Even if golang doesn't break backward, using features of newer versions maybe break those. That exactly matches releng concern with python version.

**Pull request merged**
