### PR TITLE
Return context.Err() if context was aborted

### PR DESCRIPTION
**Pull request by jonasfj**
Returning the `context.Err()` is a good pattern as
comparing to `context.Canceled` and `context.DeadlineExceeded` is a common pattern.

Wrapping the exception in an other exception is not helpful here. Often we don't really
know how to handle errors, but we do know how to handle an error occuring from a cancelation.

### CODE REVIEW

**Review by petemoore — CHANGES_REQUESTED** [review]
```
 60 // New returns a Queue client, configured to run against production. Pass in
 61 // nil to create a client without authentication. The
 62 // returned client is mutable, so returned settings can be altered.
 63 //
 64 //  queue, err := tcqueue.New(nil)                         // credentials loaded from TASKCLUSTER_* env vars
 65 //  if err != nil {
 66 //      // handle malformed credentials...
 67 //  }
 68 //  queue.BaseURL = "http://localhost:1234/api/Queue/v1"   // alternative API endpoint (production by default)
 69 //  data, err := queue.Task(.....)                         // for example, call the Task(.....) API endpoint (described further down)...
 70 //  if err != nil {
 71 //      // handle errors...
 72 //  }
 73 func New(credentials *tcclient.Credentials) *Queue {
 74     return &Queue{
 75         Credentials:  credentials,
 76         BaseURL:      DefaultBaseURL,
 77         Authenticate: credentials != nil,
 78     }
 79 }
```

1) `"credentials loaded from TASKCLUSTER_* env vars"` ???
2) `queue, err` ??


Please check ALL the generated code before you request your next review. ;-)

**Review by petemoore — CHANGES_REQUESTED** [review]
From the [context package docs](https://golang.org/pkg/context/#pkg-overview):

Programs that use Contexts should follow these rules to keep interfaces consistent across packages and enable static analysis tools to check context propagation:

Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named `ctx`:

```go
func DoSomething(ctx context.Context, arg Arg) error {
	// ... use ctx ...
}
```

-----

I know you haven't put the context inside a struct in *this* PR, you did that in #19 - but if you are cleaning up context, taking it out of the struct should be done at the same time. The current implementation is an anti-pattern, and we shouldn't invest more effort into it.

The correct place for the context is in the generated methods, e.g.

```
func (queue *Queue) CreateTask(ctx context.Context, taskId string, payload *TaskDefinitionRequest) (*TaskStatusResponse, error) { 
    ...
}
```

**Comment by petemoore** [comment]
OK, as you've done the work, let's merge, and refactor in a different PR.

**Comment by jonasfj** [comment]
Okay, we have already merge the `rename-packages` branch... :)

So I just pushed this directly, but it should be on `master` now..

**Pull request merged**
