### PR TITLE
Mock package

### PR DESCRIPTION
**Pull request by jonasfj**
This is on top of the remove `CallSummary`
It just adds an `AbstractQueue`, etc.... interfaces.. So it's easier to generate good mocks.

We should probably make a mock package containing MockQueue objects and things like that... It would be really nice to just have it from here... Rather than having to do it everywhere else...

I'm also okay with throwing the `MockQueue` into the `queue` package... Really the go compiler probably removes code that isn't referenced (after all these are statically linked binaries).

### CODE REVIEW

**Comment by petemoore** [comment]
@jonasfj I think we can avoid doubling the number of types by making the APICall function a property of the ConnectionData.

e.g. adding `APICall` to `ConnectionData` struct, as below:

```
type ConnectionData struct {
    Credentials *Credentials
    // The URL of the API endpoint to hit.
    // Use "https://auth.taskcluster.net/v1" for production.
    // Please note calling auth.New(clientId string, accessToken string) is an
    // alternative way to create an Auth object with BaseURL set to production.
    BaseURL string
    // Whether authentication is enabled (e.g. set to 'false' when using taskcluster-proxy)
    // Please note calling auth.New(clientId string, accessToken string) is an
    // alternative way to create an Auth object with Authenticate set to true.
    Authenticate bool

    // Function to make API calls. If nil,
    // github.com/taskcluster/taskcluster-client-go#ConnectionData.APICall
    // will be used. Useful for mocking API calls in tests.
    APICall func (connectionData *ConnectionData, payload interface{}, method, route string, result interface{}, query url.Values) (interface{}, *CallSummary, error)
}
```

Let's do this instead.

**Comment by jonasfj** [comment]
Hmm... this is interesting... so have you look at the libraries for mocking objects, they make it very easy when using interfaces, so I would argue that is tempting.

**Comment by jonasfj** [comment]
Basically, the mocking is afaik better typed...

**Comment by jonasfj** [comment]
@petemoore, IMO we should sligtly rethink the go client library...

the top-level package should be `taskcluster` and `taskcluster.NewQueue(...)` should create a queue client object. The types for all the queue can still be in it's own subpackage, I don't care I would rarely have to import that... (right?)

**Comment by petemoore** [comment]
@jonasfj I think if we merge the packages, we'll get more churn on the one monolithic package if any of our services get updated, since the one package will needs to be rebuilt. It would also make it harder for people to write their own services, and build them independently, in packages that maybe they don't publish until they are ready. Also I think the godocs would be harder to read, as we would now have one extremely long godoc. For example, we get a nice package summary in the queue package, describing the purpose of the queue etc. Now the one package would need to be long enough to contain descriptions of all of our services, and the types would all be mixed in together. I like that in our JS docs we have a separate page describing each API service, and I think the package separation reflects this nicely.

About mocking - I see your point, it is nice to mock the methods, rather than just providing an alternative `APICall` function, as when mocking you probably want to intercept the higher level method call, rather than needing to know url path etc.

I think what you're saying is that implementing classes can be in a separate package, but we can also achieve this by not exporting the implementing classes, just the interfaces. This way the docs won't blow up.

Let me think about this over the weekend. Probably I'm ok with generating the interfaces, I just want to think through possible repercussions a little bit more before we go ahead.

**Comment by jonasfj** [comment]
What I mean is I want the end user interface to be:
queue := taskcluster.NewQueue()

Now the type returned from NewQueue may be a type from another package I
don't really care as long as the only package the end user have to import
is "taskcluster" then if end user wants to create say a task paylaod then
end user has to use types from the queue package... And yes NewQueue likely
returns something from the queue package too..

Note: NewQueue does not return an interface I suspect... Well, that depends
do we want to update the clientId.. I fully support client objects being
100% immutable I think that'll simplify a lot of concurrency concerns...

I think we've talked about all this before...
@petemoore perhaps a better solution is to create a new repo called
go-taskcluster and put it all there... Then not start using it until we
both like the design, have figured out mock and ensured types and decent
names... Possibly modifying schemas to facilitate that..

This way we can break compatibility aggressively a few times before we're
done... Just a suggestion we can also use gopkg.in and make a version 2,
then only switch master branch when version 2 is ready... And we break all
consumers...

**Comment by petemoore** [comment]
@jonasfj Sure, it seems reasonable to draft an alternative version. I'd prefer not to create a new project, let's just do it in this PR, and merge if we agree on a version. Since we can trace who depends on our package in godoc, if we're the only ones using it, I'd propose we break backward compatibility, and upgrade our dependent libraries at the same time to use the new API calls. No need to support the older version if we are the only ones using it, I think.

**Comment by petemoore** [comment]
If I understand correctly, the scope of this is a few things:

1) Expose interfaces for services (`Queue`, `AWSProvisioner`, `Github`, `PurgeCache`, ...) and create both concrete implementations and mocks to make testing easier for components that depend on us (e.g. taskcluster-worker)
2) Move factory methods for services into a top level package (`taskcluster.NewQueue()`, `taskcluster.NewQueueEvents()`, `taskcluster.NewAWSProvisioner()`, ...).
3) Making services (`Queue`, `AWSProvisioner`, ...) types immutable, as much as possible to avoid concurrency issues. Seems reasonable.

**Comment by jonasfj** [comment]
So doesn't this PR do 1) I can't remember...

Den 9. sep. 2016 4.28 AM skrev "Pete Moore" notifications@github.com:

**Comment by petemoore** [comment]
I also don't remember, but I think it has bit rotted in any case. 😞

**Comment by petemoore** [comment]
@jonasfj This is so old and bit-rotted now, we should probably close and start again. My leaning now is to suggest to create a separate library, and leave this one as it is. It is easier then to avoid bitrot, and applications to upgrade as and when they wish to the new library, or continue using the former library if they prefer.

**Comment by djmitche** [comment]
> @jonasfj This is so old and bit-rotted now, we should probably close and start again.

Done!

**Pull request closed without merging**
